=== healthcit/BIGR/BIGRCore/src/com/gulfstreambio/kc/resources/kcFormDefinitionXML1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- -->
<!-- FileName: kcFormDefinitionXML1.dtd-->
<!-- -->
<!ELEMENT formDefinition (formElementDefinitions, valueSetDefinitions?)>
<!ATTLIST formDefinition
	name CDATA #REQUIRED
>
<!-- -->
<!ELEMENT formElementDefinitions (categoryDefinition+ | (dataElementDefinition | hostElement)+)>
<!-- -->
<!ELEMENT categoryDefinition (categoryDefinition+ | (dataElementDefinition | hostElement)+)>
<!ATTLIST categoryDefinition
	displayName CDATA #REQUIRED
	categoryType (page | heading) #REQUIRED
>
<!-- -->
<!ELEMENT dataElementDefinition (adeElementDefinition*, tag*, calculation?)>
<!ATTLIST dataElementDefinition
	cui CDATA #REQUIRED
	required (true | false) "false"
	displayName CDATA #IMPLIED
	standardValueSetId IDREF #IMPLIED
	narrowValueSetId IDREF #IMPLIED
	displayStandardValueSet (true | false) "false"
>
<!-- -->
<!ELEMENT hostElement (tag*)>
<!ATTLIST hostElement 
	hostId CDATA #REQUIRED
	required (true | false) "false"
	displayName CDATA #IMPLIED
>
<!-- -->
<!ELEMENT valueSetDefinitions (valueSetDefinition+)>
<!-- -->
<!ELEMENT valueSetDefinition (valueDefinition+)>
<!ATTLIST valueSetDefinition
	id ID #REQUIRED
>
<!-- -->
<!ELEMENT valueDefinition (valueDefinition*)>
<!ATTLIST valueDefinition
	cui CDATA #REQUIRED
	displayName CDATA #IMPLIED
>
<!-- -->
<!ELEMENT adeElementDefinition EMPTY >
<!ATTLIST adeElementDefinition 
	cui CDATA #REQUIRED
	displayName CDATA #IMPLIED
>  
<!-- -->
<!ELEMENT tag EMPTY>
<!ATTLIST tag
	type CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!-- -->
<!ELEMENT calculation (calculation | dataElementDefinitionReference | literal)+>
<!ATTLIST calculation
	operation (add | subtract | multiply | divide) #REQUIRED
	convertResultToIntMethod CDATA #IMPLIED
>
<!-- -->
<!ELEMENT dataElementDefinitionReference EMPTY>
<!ATTLIST dataElementDefinitionReference
	cui CDATA #REQUIRED
>
<!-- -->
<!ELEMENT literal EMPTY>
<!ATTLIST literal
  dataType (int | float | date) #REQUIRED
	value CDATA #REQUIRED
>

=== healthcit/BIGR/BIGRAdmin/KC/DET15/AllComboTestInt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formDefinition PUBLIC "-//GulfStream Bioinformatics Corporation//DTD KnowledgeCapture Form Definition XML1//EN" "kcFormDefinitionXML1.dtd">
<formDefinition name="All Combo Test - int">
  <formElementDefinitions>
    <categoryDefinition displayName="no units" categoryType="page">
      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=n; EAV=n; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA12234C"/>
        <dataElementDefinition cui="CA12235C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=n; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=n; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=n; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=y; EAV=n; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=y; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=y; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=n; max=y; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=n; EAV=n; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA01234C"/>
        <dataElementDefinition cui="CA00173C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=n; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=n; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=n; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=y; EAV=n; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA00053C"/>
        <dataElementDefinition cui="CA11592C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=y; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=y; EAV=y; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA07641C"/>
        <dataElementDefinition cui="CA02486C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=n; min=y; max=y; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
    </categoryDefinition>
    <categoryDefinition displayName="units" categoryType="page">
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=n; EAV=n; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=n; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=n; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=n; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=y; EAV=n; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=y; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=y; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=n; max=y; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=n; EAV=n; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA01326C"/>
        <dataElementDefinition cui="CA11948C"/>
      </categoryDefinition>
      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=n; EAV=n; ADE=y" categoryType="heading">
        <dataElementDefinition cui="CA06331C"/>
      </categoryDefinition>
      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=n; EAV=y; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA07954C"/>
        <dataElementDefinition cui="CA07964C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=n; EAV=y; ADE=y" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=y; EAV=n; ADE=n" categoryType="heading">
        <dataElementDefinition cui="CA11764C"/>
        <dataElementDefinition cui="CA11771C"/>
      </categoryDefinition>
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=y; EAV=n; ADE=y" categoryType="heading">
      </categoryDefinition> -->
<!--      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=y; EAV=y; ADE=n" categoryType="heading">
      </categoryDefinition> -->
      <categoryDefinition displayName="datatype=int; unit=y; min=y; max=y; EAV=y; ADE=y" categoryType="heading">
        <dataElementDefinition cui="CA02445C"/>
      </categoryDefinition>
    </categoryDefinition>
  </formElementDefinitions>
</formDefinition>

=== healthcit/BIGR/BIGRAdmin/KC/DET15/AllComboTestDate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formDefinition PUBLIC "-//GulfStream Bioinformatics Corporation//DTD KnowledgeCapture Form Definition XML1//EN" "kcFormDefinitionXML1.dtd">
<formDefinition name="All Combo Test - date">
  <formElementDefinitions>
    <categoryDefinition displayName="datatype=date; min=n; max=n; EAV=n; ADE=n" categoryType="heading">
      <dataElementDefinition cui="CA12228C"/>
      <dataElementDefinition cui="CA12229C"/>
    </categoryDefinition>
<!--    <categoryDefinition displayName="datatype=date; min=n; max=n; EAV=n; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=n; max=n; EAV=y; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=n; max=n; EAV=y; ADE=y" categoryType="heading">
    </categoryDefinition> -->
    <categoryDefinition displayName="datatype=date; min=n; max=y; EAV=n; ADE=n" categoryType="heading">
      <dataElementDefinition cui="CA01335C"/>
      <dataElementDefinition cui="CA03284C"/>
    </categoryDefinition>
<!--    <categoryDefinition displayName="datatype=date; min=n; max=y; EAV=n; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=n; max=y; EAV=y; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=n; max=y; EAV=y; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=n; EAV=n; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=n; EAV=n; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=n; EAV=y; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=n; EAV=y; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=y; EAV=n; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=y; EAV=n; ADE=y" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=y; EAV=y; ADE=n" categoryType="heading">
    </categoryDefinition> -->
<!--    <categoryDefinition displayName="datatype=date; min=y; max=y; EAV=y; ADE=y" categoryType="heading">
    </categoryDefinition> -->
  </formElementDefinitions>
</formDefinition>
