=== healthcit/BIGR/BIGRCore/src/com/ardais/bigr/resources/BigrLibraryMetaData.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- -->
<!-- TODO -->
<!-- 1) Make sure code enforces ALL validity rules -->
<!--		a) tableName attributes have unique values -->
<!--		b) javaConstant attributes have unique values -->
<!--		c) columnName attributes have unique values -->
<!--		d) aliasValue attributes have unique values -->
<!--		e) keyName attributes have unique values -->
<!--		f) ordering attributes have unique values -->
<!--		g) tableAlias attributes reference table aliases -->
<!--		h) columnAlias attributes reference column aliases -->
<!--		h) columnName attributes reference columns -->
<!-- FileName: BigrLibraryMetaData.dtd-->
<!-- -->
<!ELEMENT bigrLibraryMetaData (dbTable*, table*, column*, columnCount*, filterEqual*, filterNotEqual*, filterGreaterThan*, filterLike*, filterNotLike*, filterIsNull*, filterNotIsNull*, filterContains*, filterNumericRange*, filterDateRange*, filterNvlEqual*, filterNvlNotEqual*, filterJoin*, filterExists*, filterNotExists*, filterNotIn*, filterOther*, compoundFilter*)>
<!ATTLIST bigrLibraryMetaData
	version CDATA #REQUIRED
>
<!-- -->
<!ELEMENT dbTable (dbAlias*, dbColumn*)>
<!ATTLIST dbTable
	tableName CDATA #REQUIRED
	javaConstant CDATA #REQUIRED
>
<!-- -->
<!ELEMENT dbColumn (dbAlias*)>
<!ATTLIST dbColumn
	columnName CDATA #REQUIRED
	javaConstant CDATA #REQUIRED
>
<!-- -->
<!ELEMENT dbAlias EMPTY>
<!ATTLIST dbAlias
	aliasValue CDATA #REQUIRED
	javaConstant CDATA #IMPLIED
>
<!-- -->
<!ELEMENT table EMPTY>
<!ATTLIST table
	tableAlias CDATA #REQUIRED
	ordering CDATA #REQUIRED
>
<!-- -->
<!ELEMENT column EMPTY>
<!ATTLIST column
	tableAlias CDATA #REQUIRED
	columnAlias CDATA #REQUIRED
	ordering CDATA #REQUIRED
>
<!-- -->
<!ELEMENT columnCount EMPTY>
<!ATTLIST columnCount
	tableAlias CDATA #REQUIRED
	columnAlias CDATA #REQUIRED
	ordering CDATA #REQUIRED
>
<!-- -->
<!ELEMENT compoundFilter (filterKey*, hint?)>
<!ATTLIST compoundFilter
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	operator (AND | OR) #REQUIRED
	multiOperator (AND | OR) #IMPLIED
>
<!-- -->
<!ELEMENT filterKey EMPTY>
<!ATTLIST filterKey
	keyName CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterEqual (hint?)>
<!ATTLIST filterEqual
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterNotEqual (hint?)>
<!ATTLIST filterNotEqual
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterGreaterThan (hint?)>
<!ATTLIST filterGreaterThan
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterLike (hint?)>
<!ATTLIST filterLike
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterNotLike (hint?)>
<!ATTLIST filterNotLike
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterIsNull (hint?)>
<!ATTLIST filterIsNull
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterNotIsNull (hint?)>
<!ATTLIST filterNotIsNull
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterContains (hint?)>
<!ATTLIST filterContains
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterNumericRange (hint?)>
<!ATTLIST filterNumericRange
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	lowerLimit CDATA #IMPLIED
	lowerInclusive (true | false) #IMPLIED
	upperLimit CDATA #IMPLIED
	upperInclusive (true | false) #IMPLIED
>
<!-- -->
<!ELEMENT filterDateRange (hint?)>
<!ATTLIST filterDateRange
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
	lowerLimit CDATA #IMPLIED
	upperLimit CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterNvlEqual  (leftNvlValue, rightNvlValue, hint?)>
<!ATTLIST filterNvlEqual
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT leftNvlValue (fixedValue*, tableColumn*)>
<!-- -->
<!ELEMENT rightNvlValue (fixedValue*, tableColumn*)>
<!-- -->
<!ELEMENT fixedValue EMPTY>
<!ATTLIST fixedValue
	value CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterNvlNotEqual (leftNvlValue, rightNvlValue, hint?)>
<!ATTLIST filterNvlNotEqual
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!-- -->
<!ELEMENT filterExists (selectClause, hint?)>
<!ATTLIST filterExists 
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
>

<!ELEMENT selectClause (columnOrValueList, fromTable, whereClause)>
<!ELEMENT columnOrValueList (fixedValue*, tableColumn*)>
<!ELEMENT fromTable (dbAlias+)>
<!ELEMENT whereClause (filterKey*)>
<!ATTLIST whereClause 
	operator (AND | OR) #IMPLIED
>
<!-- -->
<!ELEMENT filterNotExists (selectClause, hint?)>
<!ATTLIST filterNotExists 
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterNotIn (tableColumn, selectClause, hint?)>
<!ATTLIST filterNotIn 
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterJoin (leftColumn, rightColumn, hint?)>
<!ATTLIST filterJoin
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	joinType (left | right | inner) #IMPLIED
>
<!ELEMENT leftColumn (tableColumn)>
<!ELEMENT rightColumn (tableColumn)>
<!-- -->
<!ELEMENT tableColumn EMPTY>
<!ATTLIST tableColumn
	tableAlias CDATA #REQUIRED
	columnName CDATA #REQUIRED
>
<!-- -->
<!ELEMENT filterOther (hint?)>
<!ATTLIST filterOther
	keyName CDATA #REQUIRED
	ordering CDATA #REQUIRED
	sqlString CDATA #REQUIRED
	multiOperator (AND | OR) #IMPLIED
>

<!ELEMENT hint EMPTY>
<!ATTLIST hint
	hintPriority CDATA #REQUIRED
	hintText CDATA #REQUIRED
>

=== healthcit/BIGR/BIGRCore/src/com/ardais/bigr/resources/BigrLibraryMetaData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bigrLibraryMetaData PUBLIC "-//Ardais Corporation//DTD Bigr Library Meta Data 1.0//EN" "BigrLibraryMetaData.dtd">
<bigrLibraryMetaData version="1.0">
	<dbTable tableName="iltds_asm" javaConstant="TABLE_ASM">
		<dbAlias aliasValue="asm"/>
		<dbColumn columnName="specimen_type" javaConstant="ASM_APPEARANCE">
			<dbAlias aliasValue="gross_appearance"/>
		</dbColumn>
		<dbColumn columnName="ardais_id" javaConstant="ASM_DONOR_ID">
			<dbAlias aliasValue="asm_ardais_id"/>
		</dbColumn>
		<dbColumn columnName="consent_id" javaConstant="ASM_CONSENT_ID">
			<dbAlias aliasValue="asm_consent_id"/>
		</dbColumn>
		<dbColumn columnName="asm_id" javaConstant="ASM_ID">
			<dbAlias aliasValue="asm_id"/>
		</dbColumn>
		<dbColumn columnName="asm_form_id" javaConstant="ASM_FORM_ID">
			<dbAlias aliasValue="asm_form_id"/>
		</dbColumn>
		<dbColumn columnName="organ_site_concept_id" javaConstant="ASM_TISSUE">
			<dbAlias aliasValue="asm_tissue"/>
		</dbColumn>
		<dbColumn columnName="organ_site_concept_id_other" javaConstant="ASM_TISSUE_OTHER">
			<dbAlias aliasValue="asm_tissue_other"/>
		</dbColumn>
		<dbColumn columnName="module_comments" javaConstant="ASM_MODULE_COMMENTS">
			<dbAlias aliasValue="module_comments"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_asm_form" javaConstant="TABLE_ASM_FORM">
		<dbAlias aliasValue="asm_form"/>
		<dbColumn columnName="ardais_id" javaConstant="ASM_FORM_DONOR_ID">
			<dbAlias aliasValue="asm_form_ardais_id"/>
		</dbColumn>
		<dbColumn columnName="consent_id" javaConstant="ASM_FORM_CONSENT_ID">
			<dbAlias aliasValue="asm_form_consent_id"/>
		</dbColumn>
		<dbColumn columnName="asm_form_id" javaConstant="ASM_FORM_FORM_ID">
			<dbAlias aliasValue="asm_form_form_id"/>
		</dbColumn>
		<dbColumn columnName="ardais_staff_id" javaConstant="ASM_FORM_PREPARED_BY">
			<dbAlias aliasValue="asm_form_prepared_by"/>
		</dbColumn>
		<dbColumn columnName="surgical_specimen_id" javaConstant="ASM_FORM_PROCEDURE">
			<dbAlias aliasValue="asm_form_procedure"/>
		</dbColumn>
		<dbColumn columnName="surgical_specimen_id_other" javaConstant="ASM_FORM_PROCEDURE_OTHER">
			<dbAlias aliasValue="asm_form_procedure_other"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_attachments" javaConstant="TABLE_ATTACHMENTS">
		<dbAlias aliasValue="attachments"/>
		<dbColumn columnName="id" javaConstant="ATTACHMENTS_ID">
			<dbAlias aliasValue="attach_id"/>
		</dbColumn>
		<dbColumn columnName="ardais_acct_key" javaConstant="ATTACHMENTS_ADS_ACCT_KEY">
			<dbAlias aliasValue="attach_ardais_acct_key"/>
		</dbColumn>
		<dbColumn columnName="ardais_id" javaConstant="ATTACHMENTS_DONOR_ID">
			<dbAlias aliasValue="attach_ardais_id"/>
		</dbColumn>
		<dbColumn columnName="consent_id" javaConstant="ATTACHMENTS_CONSENT_ID">
			<dbAlias aliasValue="attach_consent_id"/>
		</dbColumn>		
		<dbColumn columnName="sample_barcode_id" javaConstant="ATTACHMENTS_SAMPLE_BARCODE_ID">
			<dbAlias aliasValue="attach_sample_barcode_id"/>
		</dbColumn>
		<dbColumn columnName="is_phi_yn" javaConstant="ATTACHMENTS_ISPHI">
			<dbAlias aliasValue="attach_is_phi_yn"/>
		</dbColumn>
		<dbColumn columnName="comments" javaConstant="ATTACHMENTS_COMMENTS">
			<dbAlias aliasValue="attach_comments"/>
		</dbColumn>
		<dbColumn columnName="name" javaConstant="ATTACHMENTS_NAME">
			<dbAlias aliasValue="attach_name"/>
		</dbColumn>
		<dbColumn columnName="attachment" javaConstant="ATTACHMENTS_ATTACHED">
			<dbAlias aliasValue="attach_attachment"/>
		</dbColumn>
		<dbColumn columnName="created_by" javaConstant="ATTACHMENTS_CREATED_BY">
			<dbAlias aliasValue="attach_created_by"/>
		</dbColumn>
		<dbColumn columnName="created_date" javaConstant="ATTACHMENTS_CREATED_DATE">
			<dbAlias aliasValue="attach_created_date"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_box_location" javaConstant="TABLE_BOX_LOCATION">
		<dbAlias aliasValue="box_location"/>
		<dbColumn columnName="box_barcode_id" javaConstant="BOX_LOCATION_BOX_BARCODE_ID">
			<dbAlias aliasValue="box_location_box_barcode_id"/>
		</dbColumn>
		<dbColumn columnName="location_address_id" javaConstant="BOX_LOCATION_ADDRESS_ID">
			<dbAlias aliasValue="box_location_id"/>
		</dbColumn>		
		<dbColumn columnName="room_id" javaConstant="BOX_LOCATION_ROOM_ID">
			<dbAlias aliasValue="box_location_room_id"/>
		</dbColumn>		
		<dbColumn columnName="drawer_id" javaConstant="BOX_LOCATION_DRAWER_ID">
			<dbAlias aliasValue="box_location_drawer_id"/>
		</dbColumn>		
		<dbColumn columnName="slot_id" javaConstant="BOX_LOCATION_SLOT_ID">
			<dbAlias aliasValue="box_location_slot_id"/>
		</dbColumn>
		<dbColumn columnName="unit_name" javaConstant="BOX_LOCATION_UNIT_NAME">
			<dbAlias aliasValue="box_location_unit_name"/>
		</dbColumn>
		<dbColumn columnName="storage_type_cid" javaConstant="BOX_LOCATION_STORAGE_TYPE_CID">
			<dbAlias aliasValue="box_location_storage_type_cid"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_ardais_staff" javaConstant="TABLE_ARDAIS_STAFF">
		<dbAlias aliasValue="staff"/>
		<dbColumn columnName="ardais_staff_id" javaConstant="ARDAIS_STAFF_STAFF_ID">
			<dbAlias aliasValue="staff_id"/>
		</dbColumn>
		<dbColumn columnName="location_address_id" javaConstant="STAFF_LOCATION_ADDRESS_ID">
			<dbAlias aliasValue="staff_location_id"/>
		</dbColumn>		
		<dbColumn columnName="ardais_staff_lname" javaConstant="ARDAIS_STAFF_STAFF_LNAME">
			<dbAlias aliasValue="ardais_staff_staff_lname"/>
		</dbColumn>
		<dbColumn columnName="ardais_staff_fname" javaConstant="ARDAIS_STAFF_STAFF_FNAME">
			<dbAlias aliasValue="ardais_staff_staff_fname"/>
		</dbColumn>
		<dbColumn columnName="ardais_acct_key" javaConstant="ARDAIS_STAFF_ACCT_KEY">
			<dbAlias aliasValue="ardais_staff_acct_key"/>
		</dbColumn>
		<dbColumn columnName="ardais_user_id" javaConstant="ARDAIS_STAFF_USER_ID">
			<dbAlias aliasValue="ardais_staff_user_id"/>
		</dbColumn>
	</dbTable>	
	<dbTable tableName="iltds_informed_consent" javaConstant="TABLE_CONSENT">
		<dbAlias aliasValue="consent"/>
		<dbColumn columnName="consent_id" javaConstant="CONSENT_ID">
			<dbAlias aliasValue="consent_id"/>
			<dbAlias aliasValue="consent_count" javaConstant="DONOR_CONSENT_COUNT"/>
		</dbColumn>
		<dbColumn columnName="disease_concept_id" javaConstant="CONSENT_DX">
			<dbAlias aliasValue="consent_dx"/>
		</dbColumn>
		<dbColumn columnName="disease_concept_id_other" javaConstant="CONSENT_DX_OTHER">
			<dbAlias aliasValue="consent_dx_other"/>
		</dbColumn>
		<dbColumn columnName="linked" javaConstant="CONSENT_LINKED"/>
		<dbColumn columnName="consent_location_address_id" javaConstant="CONSENT_LOCATION">
			<dbAlias aliasValue="consent_location"/>
		</dbColumn>
		<dbColumn columnName="consent_pull_datetime" javaConstant="CONSENT_PULL_DT">
			<dbAlias aliasValue="consent_pull_datetime"/>
		</dbColumn>
		<dbColumn columnName="ardais_id" javaConstant="DONOR_ID">
			<dbAlias aliasValue="ardais_id"/>
		</dbColumn>
		<dbColumn columnName="best_diagnosis_cui" javaConstant="CONSENT_BEST_DIAGNOSIS_CUI">
			<dbAlias aliasValue="best_diagnosis_cui"/>
		</dbColumn>
		<dbColumn columnName="best_diagnosis_other" javaConstant="CONSENT_BEST_DIAGNOSIS_OTHER">
			<dbAlias aliasValue="best_diagnosis_other"/>
		</dbColumn>
		<dbColumn columnName="ardais_acct_key" javaConstant="CONSENT_ARDAIS_ACCT_KEY">
			<dbAlias aliasValue="consent_ardais_acct_key"/>
		</dbColumn>
		<dbColumn columnName="imported_yn" javaConstant="CONSENT_IMPORTED_YN">
			<dbAlias aliasValue="consent_imported_yn"/>
		</dbColumn>
		<dbColumn columnName="customer_id" javaConstant="CONSENT_CUSTOMER_ID">
			<dbAlias aliasValue="consent_customer_id"/>
		</dbColumn>
		<dbColumn columnName="psa" javaConstant="CONSENT_PSA">
			<dbAlias aliasValue="consent_psa"/>
		</dbColumn>
		<dbColumn columnName="dre_cid" javaConstant="CONSENT_DRE_CID">
			<dbAlias aliasValue="consent_dre_cid"/>
		</dbColumn>
		<dbColumn columnName="clinical_finding_notes" javaConstant="CONSENT_CLINICAL_FINDING_NOTES">
			<dbAlias aliasValue="consent_clinical_finding_notes"/>
		</dbColumn>
		<dbColumn columnName="policy_id" javaConstant="CONSENT_POLICY_ID">
			<dbAlias aliasValue="consent_policy_id"/>
		</dbColumn>
		<dbColumn columnName="case_registration_form" javaConstant="CONSENT_REG_FORM">
			<dbAlias aliasValue="consent_reg_form"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_revoked_consent_archive" javaConstant="TABLE_CONSENT_REVOKED">
		<dbAlias aliasValue="revoked_consent"/>
		<dbColumn columnName="consent_id" javaConstant="REVOKED_CONSENT_ID">
			<dbAlias aliasValue="revoked_consent_id"/>
		</dbColumn>
	</dbTable>
	<dbTable tableName="iltds_sample" javaConstant="TABLE_SAMPLE">
		<dbAlias aliasValue="sample"/>
		<dbAlias aliasValue="sample1" javaConstant="TABLE_SAMPLE1"/>
		<dbColumn columnName="ardais_acct_key" javaConstant="SAMPLE_ACCOUNT">
			<dbAlias aliasValue="sample_ardais_acct_key"/>
		</dbColumn>
		<dbColumn columnName="asm_id" javaConstant="SAMPLE_ASM_ID">
			<dbAlias aliasValue="sample_asm_id"/>
		</dbColumn>
		<dbColumn columnName="asm_position" javaConstant="SAMPLE_ASM_POSITION">
			<dbAlias aliasValue="asm_position"/>
		</dbColumn>
		<dbColumn columnName="di_max_thickness_pfin_cid" javaConstant="SAMPLE_DI_MAX_THICKNESS">
			<dbAlias aliasValue="di_max_thickness_pfin_cid"/>
		</dbColumn>
		<dbColumn columnName="di_min_thickness_pfin_cid" javaConstant="SAMPLE_DI_MIN_THICKNESS">
			<dbAlias aliasValue="di_min_thickness_pfin_cid"/>
		</dbColumn>
		<dbColumn columnName="di_width_across_pfin_cid" javaConstant="SAMPLE_DI_WIDTH">
			<dbAlias aliasValue="di_width_across_pfin_cid"/>
		</dbColumn>
		<dbColumn columnName="discordant_yn" javaConstant="SAMPLE_DISCORDANT">
			<dbAlias aliasValue="discordant_yn"/>
		</dbColumn>
		<dbColumn columnName="format_detail_cid" javaConstant="SAMPLE_FORMAT_DETAIL">
			<dbAlias aliasValue="format_detail_cid"/>
		</dbColumn>
		<dbColumn columnName="type_of_fixative" javaConstant="SAMPLE_FIXATIVE_TYPE">
