=== healthcit/BIGR/BIGRCore/src/com/ardais/bigr/resources/btxConfig.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- FileName: btxConfig.dtd-->
<!--
  ** Transaction configuration file for the BTX framework.
  -->

<!-- -->
<!ELEMENT btxConfig (transactions)>

<!-- -->
<!ELEMENT transactions (transaction*)>

<!-- -->
<!ELEMENT transaction (set-property*)>
<!ATTLIST transaction
	type ID #REQUIRED
	performerType NMTOKEN #REQUIRED
	performerMethod NMTOKEN #REQUIRED
	validate (true | false) #IMPLIED
	validatorMethod NMTOKEN #IMPLIED
>

<!-- -->
<!ELEMENT set-property EMPTY>
<!ATTLIST set-property
	property NMTOKEN #REQUIRED
	value NMTOKEN #REQUIRED
>

=== healthcit/BIGR/BIGRCore/src/com/ardais/bigr/resources/btxConfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE btxConfig PUBLIC
    "-//Ardais Corporation//DTD BTX Configuration 1.0//EN"
    "btxConfig.dtd">

<btxConfig>
  <transactions>
    <!-- ========== bigr ======================== -->
    <transaction type="bigr_update_computed_data"
      performerType="com.ardais.bigr.performers.BtxPerformerComputedDataOperation"
      performerMethod="performUpdateComputedData"
      validate="false"
    />
    <transaction type="bigr_update_computed_data_single"
      performerType="com.ardais.bigr.performers.BtxPerformerComputedDataOperation"
      performerMethod="performUpdateComputedDataSingle"
      validate="false"
    />
    <!-- ========== bigr ======================== -->
    <!-- ========== Begin Sample Selection ======================== -->
    <transaction type="library_get_sample_summary_start"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetSampleSummaryStart"
      validate="false"
    />    
    <transaction type="library_get_sample_summary"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetSampleSummary"
      validate="false"
    />
    <transaction type="library_get_sample_summary_sql"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetSampleSummarySql"
      validate="false"
    />
    <transaction type="library_get_rna_summary"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetRnaSummary"
      validate="false"
    />
    <transaction type="library_get_rna_summary_sql"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetRnaSummarySql"
      validate="false"
    />
    <transaction type="library_get_summary_no_implied"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetSummaryNoImplied"
      validate="false"
    />
    <transaction type="library_get_details"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetDetails"
      validate="false"
    />
    <transaction type="library_set_unavailable_for_pick_list"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performSetUnavailableForPickList"
      validate="false"
    />

    <transaction type="library_get_rna_representative_sample"
      performerType="com.ardais.bigr.library.performers.BtxPerformerRnaOperation"
      performerMethod="performGetRnaWithRepresentativeSample"
    />
    <transaction type="library_get_hold_list_data"
      performerType="com.ardais.bigr.library.performers.BtxPerformerHoldListManager"
      performerMethod="performGetHoldListData"
      validate="false"
    />
    <transaction type="library_add_to_hold_list"
      performerType="com.ardais.bigr.library.performers.BtxPerformerHoldListManager"
      performerMethod="performAddToHoldList"
      validate="false"
    />
    <transaction type="library_remove_from_hold_list"
      performerType="com.ardais.bigr.library.performers.BtxPerformerHoldListManager"
      performerMethod="performRemoveFromHoldList"
      validate="false"
    />
    <transaction type="library_get_order_line_data"
      performerType="com.ardais.bigr.library.performers.BtxPerformerOrderLineManager"
      performerMethod="performGetOrderLineData"
      validate="false"
    />
    <transaction type="library_get_kc_query_form"
      performerType="com.ardais.bigr.library.performers.BtxPerformerSampleSelection"
      performerMethod="performGetKcQueryForm"
      validate="false"
    />    
    <!-- ========== End Sample Selection ======================== -->
    <!-- ========== Begin ILTDS =================================== -->
    <transaction type="iltds_allocation_logAllocateSingle"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerSampleOperations"
      performerMethod="performLogAllocateSingle"
      validate="false"
    />
    <transaction type="iltds_sample_logCreateSample"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerSampleOperations"
      performerMethod="performLogCreateSample"
      validate="false"
    />
    <transaction type="iltds_case_createCase"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerCaseOperations"
      performerMethod="performCreateCase"
      validate="true"
    />
    <transaction type="iltds_shipping_createManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performCreateManifest"
      validate="true"
    />
    <transaction type="iltds_shipping_printManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performPrintManifest"
      validate="true"
    />
    <transaction type="iltds_shipping_scanpkg_getManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performGetManifest"
      validatorMethod="validatePerformGetManifestForScanAndPackage"
      validate="true"
    />
    <transaction type="iltds_shipping_confirmBoxOnManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performConfirmBoxOnManifest"
      validate="true"
    />
    <transaction type="iltds_shipping_shipManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performShipManifest"
      validate="true"
    />
    <transaction type="iltds_shipping_updateRequestsAfterShipment"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performUpdateRequestsAfterShipment"
      validate="true"
    />
    <transaction type="iltds_request_createRequestStart"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performCreateRequestStart"
      validate="true"
    />
    <transaction type="iltds_request_createRequest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performCreateRequest"
      validate="true"
    />
    <transaction type="iltds_request_manageRequests"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performManageRequests"
      validate="true"
    />
    <transaction type="iltds_request_viewRequests"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFindUserRequests"
      validate="true"
    />
    <transaction type="iltds_request_rejectRequestStart"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFindRequestDetails"
      validatorMethod="validatePerformRejectRequestStart"
      validate="true"
    />
    <transaction type="iltds_request_rejectRequest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performRejectRequest"
      validate="true"
    />
    <transaction type="iltds_request_fulfillRequestStart"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFindRequestDetails"
      validatorMethod="validatePerformFulfillRequestStart"
      validate="true"
    />
    <transaction type="iltds_request_fulfillRequestAddBox"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFulfillRequestAddBox"
      validate="true"
    />
    <transaction type="iltds_request_fulfillRequestNoOp"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFulfillRequestNoOp"
      validate="false"
    />
    <transaction type="iltds_request_fulfillRequest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFulfillRequest"
      validate="true"
    />
    <transaction type="iltds_request_findRequestDetails"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerRequestOperations"
      performerMethod="performFindRequestDetails"
      validate="true"
    />
    <transaction type="iltds_receipt_shipmentVerification"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performShipmentReceiptVerification"
      validate="true"
    />
    <transaction type="iltds_receipt_boxVerification"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performBoxReceiptVerification"
      validate="false"
    />
    <transaction type="iltds_receipt_scanShipmentInformation"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performScanShipmentInformation"
      validate="true"
    />
    <transaction type="iltds_receipt_scanAndStoreBox"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performScanAndStoreBox"
      validate="true"
    />
    <transaction type="iltds_receipt_scanAndStoreManifest"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performScanAndStoreManifest"
      validate="true"
    />
    <transaction type="iltds_receipt_printPutAwayTicket"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerShippingOperations"
      performerMethod="performPrintPutAwayTicket"
      validate="true"
    />
    <transaction type="iltds_box_checkOutBox"
      performerType="com.ardais.bigr.iltds.performers.BtxPerformerBoxOperations"
